```dockerfile
FROM node:22-bookworm AS frontend

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY resources ./resources

COPY public ./public

COPY vite.config.js ./

COPY postcss.config.js ./

RUN npm run build


FROM dunglas/frankenphp:php8.2-bookworm

RUN install-php-extensions \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

COPY isrgrootx1.pem /etc/ssl/certs/isrgrootx1.pem

COPY --from=frontend /app/public/build ./public/build

RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN php artisan config:clear && php artisan route:clear && php artisan view:clear

ENV SERVER_NAME=:8000

EXPOSE 8000

CMD ["sh", "-c", "php artisan octane:frankenphp --host=0.0.0.0 --port=${PORT:-8000}"]
```
